#ifndef STRATEGYANALYSISMOD_GLOBAL_H
#define STRATEGYANALYSISMOD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STRATEGYANALYSISMOD_LIBRARY)
#  define SAM_EXPORT Q_DECL_EXPORT
#else
#  define SAM_EXPORT Q_DECL_IMPORT
#endif

#endif // STRATEGYANALYSISMOD_GLOBAL_H
